name: django CI
on: 
  push:
    branch: [ "main" ]
  pull_request:
    branches: [ "main" ]

  jobs:
    build:
      runs-on: ubuntu-latest
      strategy: 
        max-parallel: 1
        matrix:
          python-version: [3.7, 3.8, 3.]
      steps:
        -uses: actions/checkout@v2
        -name: set up python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
        -name: install dependencies 
        run: |
          python -m pip install --upgrade pip 
          pip install -r requriments.txt
        -name: run test 
        run: |
          python manage.py test

        